spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fornecedor
    username: root
    password: root

  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
